name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # This specifies a Linux environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Use your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/src/requirements.txt # Installs all dependencies from the file

    - name: Build Sphinx documentation
      run: |
        # Navigates into the documentation source directory
        cd python/src/sphinx_docs 
        python -m sphinx -b html . _build 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./python/src/sphinx_docs/_build/html # Path to your built HTML
        publish_branch: gh-pages
        enable_jekyll: false